create table if not exists public.user_upgrade_requests (
  id_request bigint generated by default as identity primary key,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  applicant_name text not null,
  applicant_email text not null,
  specialty_category_id smallint not null references public.event_category(id_event_category) on update cascade on delete restrict,
  is_company boolean not null default false,
  company_identifier text,
  reason text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  constraint user_upgrade_requests_status_check check (status in ('pending', 'approved', 'rejected'))
);

create index if not exists idx_user_upgrade_requests_auth_user on public.user_upgrade_requests (auth_user_id);

alter table public.user_upgrade_requests enable row level security;

drop policy if exists "Upgrade requests are readable by owners and admins" on public.user_upgrade_requests;
create policy "Upgrade requests are readable by owners and admins"
on public.user_upgrade_requests
for select
using (
  auth.uid() = auth_user_id
  or public.current_user_is_admin()
);

drop policy if exists "Upgrade requests are insertable by owners" on public.user_upgrade_requests;
create policy "Upgrade requests are insertable by owners"
on public.user_upgrade_requests
for insert
with check (
  auth.uid() = auth_user_id
);

drop policy if exists "Upgrade requests are updatable by admins" on public.user_upgrade_requests;
create policy "Upgrade requests are updatable by admins"
on public.user_upgrade_requests
for update
using (public.current_user_is_admin())
with check (public.current_user_is_admin());

grant select, insert, update on public.user_upgrade_requests to authenticated;